//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KBFileTable
    {
        public KBFileTable()
        {
            this.KBNRTable = new HashSet<KBNRTable>();
        }
    
        public string Guid_kbfile { get; set; }
        public string FilePath { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string KMName { get; set; }
        public string BZ { get; set; }
        public Nullable<bool> ISCD { get; set; }
        public Nullable<bool> IsCY { get; set; }
    
        public virtual ICollection<KBNRTable> KBNRTable { get; set; }
    }
}
