//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KBNRTable
    {
        public string Guid_Kb { get; set; }
        public string KB_RQ { get; set; }
        public string KB_XQ { get; set; }
        public string KB_ZYM { get; set; }
        public string KB_NR { get; set; }
        public string KB_JYM { get; set; }
        public string KB_SKBJ { get; set; }
        public string KB_SJD { get; set; }
        public string KB_SJFW { get; set; }
        public string KB_ZYLX { get; set; }
        public string Guid_KBID { get; set; }
    
        public virtual KBFileTable KBFileTable { get; set; }
    }
}
